<a href="https://colab.research.google.com/github/Phuong181003/ecommerce/blob/main/ecommerce_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LOADING DATA

In [21]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [22]:
%cd /content/drive/MyDrive/Ecommerce_dataset
!ls

/content/drive/MyDrive/Ecommerce_dataset
ecommerce_customer.csv	ecommerce_order.csv


In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
df_order = pd.read_csv("ecommerce_order.csv")
df_cus = pd.read_csv("ecommerce_customer.csv")

# CLEAN DATA



## CHECK NULL VALUE


**FOR ORDER DATA**

In [25]:
df_order

additional_order_items       category_name  customer_id market  \
0            Camping & Hiking    Camping & Hiking          568  LATAM   
1            Camping & Hiking    Camping & Hiking         3341  LATAM   
2            Camping & Hiking    Camping & Hiking         7459  LATAM   
3            Camping & Hiking    Camping & Hiking         7459  LATAM   
4          Hunting & Shooting  Hunting & Shooting        10740  LATAM   
...                       ...                 ...          ...    ...   
115741           Water Sports        Water Sports         2666   USCA   
115742          Shop By Sport       Shop By Sport         8100   USCA   
115743                Fishing             Fishing         2666   USCA   
115744                Fishing             Fishing         9547   USCA   
115745             Golf Balls          Golf Balls        11747   USCA   

        order_date  order_id     order_region  order_quantity  product_price  \
0       17-06-2017     61558    South America               1     299.980011   
1       18-04-2017     57472    South America               1     299.980011   
2       24-05-2017     59898  Central America               1     299.980011   
3       24-05-2017     59898  Central America               1     299.980011   
4         5/6/2017     58644  Central America               1     149.990005   
...            ...       ...              ...             ...            ...   
115741  13-04-2016     32105        US Center               1     199.990005   
115742    7/2/2016     37555      East of USA               1      39.990002   
115743  13-04-2016     32105        US Center               1     399.980011   
115744    8/6/2016     39980      West of USA               1     399.980011   
115745  26-04-2016     32995      West of USA               1      14.990000   

       profit_margin  profit_per_order  
0             26.10%         78.290001  
1             -5.40%        -16.200001  
2              3.90%         11.620000  
3             -1.10%         -3.390000  
4            -63.80%        -95.650002  
...              ...               ...  
115741        27.50%         55.090000  
115742        37.40%         14.940000  
115743        39.80%        159.350006  
115744        24.90%         99.599998  
115745        39.80%          5.970000  

[115746 rows x 11 columns]



> The data in two columns 'additional_order_items' and 'category_name' look like nearly the same.
Check this assumption



In [26]:
df_order.isna().sum()

additional_order_items    1024
category_name                0
customer_id                  0
market                       0
order_date                   0
order_id                     0
order_region                 0
order_quantity               0
product_price                0
profit_margin                0
profit_per_order             0
dtype: int64

In [27]:
df_test = df_order[df_order["additional_order_items"] != df_order["category_name"]]

In [28]:
df_test["additional_order_items"].unique()

array([nan], dtype=object)

In [29]:
df_test["category_name"].unique()

array(['Accessories'], dtype=object)

In [30]:
len(df_test)

1024



> Data in 'additional_order_items' column have null 1024 rows are respectively with 1024 rows of "Accessories" in 'category_name' column. Thats why we can eliminate column 'additional_order_items' and use 'category_name' represent for both column



In [31]:
df_test.drop('additional_order_items',axis='columns', inplace=True)

<ipython-input-31-d8c4c10eb0f0>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test.drop('additional_order_items',axis='columns', inplace=True)


**FOR CUSTOMER DATA**

In [32]:
df_cus

customer_city customer_country customer_fname  customer_id  \
0             Caguas      Puerto Rico           Sean          568   
1             Caguas      Puerto Rico          Carol         3341   
2           Mayaguez      Puerto Rico           Mary         7459   
3           Mayaguez      Puerto Rico           Mary         7459   
4             Caguas      Puerto Rico           Mary        10740   
...              ...              ...            ...          ...   
115741   Los Angeles    United States           Mary         2666   
115742        Upland    United States       Victoria         8100   
115743   Los Angeles    United States           Mary         2666   
115744   Los Angeles    United States           Mary         9547   
115745     Las Vegas    United States           Mary        11747   

       customer_segment customer_state  customer_zipcode  
0              Consumer             PR             725.0  
1              Consumer             PR             725.0  
2              Consumer             PR             680.0  
3              Consumer             PR             680.0  
4              Consumer             PR             725.0  
...                 ...            ...               ...  
115741        Corporate             CA           90033.0  
115742        Corporate             CA           91786.0  
115743        Corporate             CA           90033.0  
115744        Corporate             CA           90027.0  
115745        Corporate             NV           89123.0  

[115746 rows x 7 columns]

In [33]:
df_cus.isna().sum()

customer_city       0
customer_country    0
customer_fname      0
customer_id         0
customer_segment    0
customer_state      0
customer_zipcode    3
dtype: int64

In [34]:
df_cus[df_cus["customer_zipcode"].isna()]

customer_city customer_country customer_fname  customer_id  \
21035            CA    United States           Zena        14046   
34002            CA    United States        Eugenia        17171   
50076            CA    United States           Sara        14577   

      customer_segment customer_state  customer_zipcode  
21035         Consumer          91732               NaN  
34002        Corporate          95758               NaN  
50076         Consumer          95758               NaN

In [35]:
df_cus["customer_state"].value_counts()

PR       44458
CA       18682
NY        7315
TX        5924
IL        4882
FL        3487
OH        2639
MI        2455
PA        2396
NJ        2070
AZ        1939
GA        1711
MD        1538
CO        1202
NC        1183
VA        1153
OR        1097
MA         995
NV         959
TN         942
MO         877
HI         806
NM         673
UT         658
CT         652
WA         637
LA         587
WI         575
MN         454
SC         433
IN         376
DC         330
KY         291
KS         289
DE         171
RI         170
WV         148
OK         135
ND         130
AR         100
ID          90
MT          53
IA          48
AL          33
95758        2
91732        1
Name: customer_state, dtype: int64

> From this insight, we can see that the 3 rows have the null values in *customer_zipcode* is having the different types of *customer_state*. Other *customer_state* variable is the abbreviation of the their *customer_country*, except for this 3 values. I assume that maybe the Nan value in *customer_zipcode* is the 3 different variable in *customer_country*

In [36]:
df_cus[(df_cus["customer_zipcode"] == 91732) | (df_cus["customer_zipcode"] == 95758)]

customer_city customer_country customer_fname  customer_id  \
1932        El Monte    United States         Cheryl         7457   
1934        El Monte    United States         Cheryl         7457   
2766        El Monte    United States           Mary         5152   
3096        El Monte    United States           Mary         1654   
3101        El Monte    United States           Mary         1654   
...              ...              ...            ...          ...   
113204      El Monte    United States         Cheryl         7457   
113881     Elk Grove    United States         Gerald         7651   
114157     Elk Grove    United States         Gerald         7651   
114161     Elk Grove    United States         Gerald         7651   
114317     Elk Grove    United States         Gerald         7651   

       customer_segment customer_state  customer_zipcode  
1932           Consumer             CA           91732.0  
1934           Consumer             CA           91732.0  
2766           Consumer             CA           91732.0  
3096          Corporate             CA           91732.0  
3101          Corporate             CA           91732.0  
...                 ...            ...               ...  
113204         Consumer             CA           91732.0  
113881         Consumer             CA           95758.0  
114157         Consumer             CA           95758.0  
114161         Consumer             CA           95758.0  
114317         Consumer             CA           95758.0  

[143 rows x 7 columns]

> There are so many records that have the *customer_zipcode* is 91732 and 95758 ( which is the *customer_state* value in 3 rows null). These records have the same *customer_state* is CA

> The data for 3 rows null have *customer_state* = CA and zipcode is respectively with the *customer_state* in their rows.

> We can change data as below

In [37]:
df_cus[df_cus["customer_zipcode"].isna()]

customer_city customer_country customer_fname  customer_id  \
21035            CA    United States           Zena        14046   
34002            CA    United States        Eugenia        17171   
50076            CA    United States           Sara        14577   

      customer_segment customer_state  customer_zipcode  
21035         Consumer          91732               NaN  
34002        Corporate          95758               NaN  
50076         Consumer          95758               NaN

In [44]:
index = df_cus[df_cus["customer_zipcode"].isna()].index
for i in index:
    df_cus.iloc[i, 6] = df_cus.iloc[i, 5] #Replace NaN value in the column 7 (customer_zipcdode) by the value in the column 6 (customer_state)
    df_cus.iloc[i, 5] = "CA" #Replace the NaN value in column 6 (customer_state) by "CA"

## CHECK DUPLICATE VALUE

In [19]:
df_order.duplicated().sum()

4

In [40]:
df_order.drop_duplicates(inplace = True)

In [45]:
df_cus.duplicated().sum()

97740

In [47]:
df_cus.drop_duplicates(inplace = True)

## Merge two tables

In [48]:
df = df_cus.merge(df_order, how = "right", on = "customer_id")

In [49]:
df

customer_city customer_country customer_fname  customer_id  \
0             Caguas      Puerto Rico           Sean          568   
1             Caguas      Puerto Rico          Carol         3341   
2           Mayaguez      Puerto Rico           Mary         7459   
3           Mayaguez      Puerto Rico           Mary         7459   
4             Caguas      Puerto Rico           Mary        10740   
...              ...              ...            ...          ...   
115737   Los Angeles    United States           Mary         2666   
115738        Upland    United States       Victoria         8100   
115739   Los Angeles    United States           Mary         2666   
115740   Los Angeles    United States           Mary         9547   
115741     Las Vegas    United States           Mary        11747   

       customer_segment customer_state customer_zipcode  \
0              Consumer             PR            725.0   
1              Consumer             PR            725.0   
2              Consumer             PR            680.0   
3              Consumer             PR            680.0   
4              Consumer             PR            725.0   
...                 ...            ...              ...   
115737        Corporate             CA          90033.0   
115738        Corporate             CA          91786.0   
115739        Corporate             CA          90033.0   
115740        Corporate             CA          90027.0   
115741        Corporate             NV          89123.0   

       additional_order_items       category_name market  order_date  \
0            Camping & Hiking    Camping & Hiking  LATAM  17-06-2017   
1            Camping & Hiking    Camping & Hiking  LATAM  18-04-2017   
2            Camping & Hiking    Camping & Hiking  LATAM  24-05-2017   
3            Camping & Hiking    Camping & Hiking  LATAM  24-05-2017   
4          Hunting & Shooting  Hunting & Shooting  LATAM    5/6/2017   
...                       ...                 ...    ...         ...   
115737           Water Sports        Water Sports   USCA  13-04-2016   
115738          Shop By Sport       Shop By Sport   USCA    7/2/2016   
115739                Fishing             Fishing   USCA  13-04-2016   
115740                Fishing             Fishing   USCA    8/6/2016   
115741             Golf Balls          Golf Balls   USCA  26-04-2016   

        order_id     order_region  order_quantity  product_price  \
0          61558    South America               1     299.980011   
1          57472    South America               1     299.980011   
2          59898  Central America               1     299.980011   
3          59898  Central America               1     299.980011   
4          58644  Central America               1     149.990005   
...          ...              ...             ...            ...   
115737     32105        US Center               1     199.990005   
115738     37555      East of USA               1      39.990002   
115739     32105        US Center               1     399.980011   
115740     39980      West of USA               1     399.980011   
115741     32995      West of USA               1      14.990000   

       profit_margin  profit_per_order  
0             26.10%         78.290001  
1             -5.40%        -16.200001  
2              3.90%         11.620000  
3             -1.10%         -3.390000  
4            -63.80%        -95.650002  
...              ...               ...  
115737        27.50%         55.090000  
115738        37.40%         14.940000  
115739        39.80%        159.350006  
115740        24.90%         99.599998  
115741        39.80%          5.970000  

[115742 rows x 17 columns]

## CONVERT DATE VALUE

Date value in String type in two formats dd/mm/yyyy and dd-mm-yyyy. Convert to dd-mm-yyyy format and datetime type

In [51]:
import datetime
from datetime import datetime

df["order_date"] = df["order_date"].apply(lambda x: x.replace("/", "-"))
df["order_date"] = df["order_date"].apply(lambda x: datetime.strptime(x, "%d-%m-%Y").date())

In [56]:
max(df["order_date"])

datetime.date(2017, 12, 31)

In [57]:
min(df["order_date"])

datetime.date(2016, 1, 1)

The data from the beginning of 2016 to the end of 2017

In [58]:
def week(x):
    if x.year == 2016:
        w = datetime.strptime("01-01-2016", "%d-%m-%Y").date()
    else:
        w = datetime.strptime("01-01-2017", "%d-%m-%Y").date()
    return (x-w).days // 7 + 1

In [60]:
df["year"] = df["order_date"].apply(lambda x: x.year)
df["month"] = df["order_date"].apply(lambda x: x.month)
df["week"] = df["order_date"].apply(week)

In [61]:
df

customer_city customer_country customer_fname  customer_id  \
0             Caguas      Puerto Rico           Sean          568   
1             Caguas      Puerto Rico          Carol         3341   
2           Mayaguez      Puerto Rico           Mary         7459   
3           Mayaguez      Puerto Rico           Mary         7459   
4             Caguas      Puerto Rico           Mary        10740   
...              ...              ...            ...          ...   
115737   Los Angeles    United States           Mary         2666   
115738        Upland    United States       Victoria         8100   
115739   Los Angeles    United States           Mary         2666   
115740   Los Angeles    United States           Mary         9547   
115741     Las Vegas    United States           Mary        11747   

       customer_segment customer_state customer_zipcode  \
0              Consumer             PR            725.0   
1              Consumer             PR            725.0   
2              Consumer             PR            680.0   
3              Consumer             PR            680.0   
4              Consumer             PR            725.0   
...                 ...            ...              ...   
115737        Corporate             CA          90033.0   
115738        Corporate             CA          91786.0   
115739        Corporate             CA          90033.0   
115740        Corporate             CA          90027.0   
115741        Corporate             NV          89123.0   

       additional_order_items       category_name market  order_date  \
0            Camping & Hiking    Camping & Hiking  LATAM  2017-06-17   
1            Camping & Hiking    Camping & Hiking  LATAM  2017-04-18   
2            Camping & Hiking    Camping & Hiking  LATAM  2017-05-24   
3            Camping & Hiking    Camping & Hiking  LATAM  2017-05-24   
4          Hunting & Shooting  Hunting & Shooting  LATAM  2017-06-05   
...                       ...                 ...    ...         ...   
115737           Water Sports        Water Sports   USCA  2016-04-13   
115738          Shop By Sport       Shop By Sport   USCA  2016-02-07   
115739                Fishing             Fishing   USCA  2016-04-13   
115740                Fishing             Fishing   USCA  2016-06-08   
115741             Golf Balls          Golf Balls   USCA  2016-04-26   

        order_id     order_region  order_quantity  product_price  \
0          61558    South America               1     299.980011   
1          57472    South America               1     299.980011   
2          59898  Central America               1     299.980011   
3          59898  Central America               1     299.980011   
4          58644  Central America               1     149.990005   
...          ...              ...             ...            ...   
115737     32105        US Center               1     199.990005   
115738     37555      East of USA               1      39.990002   
115739     32105        US Center               1     399.980011   
115740     39980      West of USA               1     399.980011   
115741     32995      West of USA               1      14.990000   

       profit_margin  profit_per_order  year  month  week  
0             26.10%         78.290001  2017      6    24  
1             -5.40%        -16.200001  2017      4    16  
2              3.90%         11.620000  2017      5    21  
3             -1.10%         -3.390000  2017      5    21  
4            -63.80%        -95.650002  2017      6    23  
...              ...               ...   ...    ...   ...  
115737        27.50%         55.090000  2016      4    15  
115738        37.40%         14.940000  2016      2     6  
115739        39.80%        159.350006  2016      4    15  
115740        24.90%         99.599998  2016      6    23  
115741        39.80%          5.970000  2016      4    17  

[115742 rows x 20 columns]

# BUSINESS OVERVIEW

In [ ]:
def line_chart(data_2016, data_20117, _type):
